### ISSUE TITLE
Section on reverse proxies shows a diagram of a forward proxy

### ISSUE THREAD

**Issue by joehorsnell** [donnemartin/system-design-primer#1]
@donnemartin - your section on reverse proxies shows a diagram (from Wikipedia) of a forward, not a reverse proxy.

Excellent resource by the way (from the sections I've looked at anyway!).

**Comment by donnemartin** [comment]
Hi @joehorsnell, nice catch!  

Interested in a pull request?  It seems like this is the image I should have linked to:  https://upload.wikimedia.org/wikipedia/commons/6/67/Reverse_proxy_h2g2bob.svg

![](https://upload.wikimedia.org/wikipedia/commons/6/67/Reverse_proxy_h2g2bob.svg)

**Comment by joehorsnell** [comment]
You're too quick! Yes, I was planning to open a PR the following day (just raised the issue so I didn't forget) but you'd already fixed it by the time I checked back 😃

**Comment by saxad** [comment]
hello hello ! test test
