### ISSUE TITLE
Anki flash cards errors

### ISSUE THREAD

**Issue by umbs** [donnemartin/system-design-primer#126]
The provided Anki flash cards is failing to load in desktop Anki software. I tried with all .apkg files

OO Design; System Design; System Design Exercises.

I'm using Anki 2.0.48 on Windows 10 laptop.

![anki_error](https://user-images.githubusercontent.com/1351872/35123532-6ccd71b2-fc57-11e7-87b3-d9cd43d62750.png)

**Comment by kbakha** [comment]
Yes, the same occured with me.

**Comment by kbakha** [comment]
Anki droid 2.0.50 - Version 2.0.50
Qt 4.8.1 PyQt 4.9.1.

**Comment by farshad1880** [comment]
i have the same problem.help me please

**Comment by SamKChang** [comment]
the same for me on ankidriod v2.8

**Comment by dvanbrug** [comment]
I found the same error.  When inspecting the file that is downloaded from the link, it looks like an HTML file.  If I go to the file in the git repo directly and download the raw version, I am able to successfully import them.  

E.g. the following link should work:  https://github.com/donnemartin/system-design-primer/blob/master/resources/flash_cards/System%20Design.apkg?raw=true

**Comment by donnemartin** [comment]
Can anyone confirm?  PRs are welcome :)
