### ISSUE TITLE
Translation on solution part for Traditional Chinese

### ISSUE THREAD

**Issue by kevingo** [donnemartin/system-design-primer#138]
Hi @donnemartin, in order to make Traditional Chinese version more complete, I want to work on the solution part. Is it ok with you?

My idea is to put the translation markdown inside each solution folder itself. For example,  I will put the mint solution at [https://github.com/donnemartin/system-design-primer/tree/master/solutions/system_design/mint/README-zh-TW.md](https://github.com/donnemartin/system-design-primer/tree/master/solutions/system_design/mint/README-zh-TW.md) here.

Any idea?

**Comment by donnemartin** [comment]
@kevingo sounds good to me, thanks for the help!

**Comment by kevingo** [comment]
@donnemartin OK, thanks!
