### ISSUE TITLE
Make the OmniGraffle template and diagrams available

### ISSUE THREAD

**Issue by ulkaio** [donnemartin/system-design-primer#15]
Hi @donnemartin , I am big fan of your work. I have a question, how you draw these nice diagram, l mean which tools did you used. Thanks. 

**EDIT by donnemartin**: 👍 to indicate interest in the templates.

**Comment by donnemartin** [comment]
Hi @ulkaio, thanks for the feedback!  I use OmniGraffle for the diagrams.

**Comment by jamescowie** [comment]
Is there any specific template in OmniGraffle you use ?

**Comment by donnemartin** [comment]
@jamescowie I have a custom set of components I created as a template, I can try to clean those up and make them available if there's interest.

**Comment by nghib** [comment]
+1

**Comment by donnemartin** [comment]
I'll re-open this issue and change the issue title.

**Comment by jamescowie** [comment]
Thanks so much @donnemartin I would be very interested in this template as I am really impressed with how clean and understandable they are. Its also really hard to find icons such as Database that you have. 

Please let me know if I can assist in cleaning them up. I would be more than happy to take that task on and free up some of your time if it makes sense.

**Comment by donnemartin** [comment]
@jamescowie no problem, I'm working on them already :)

Hope to have them out sometime next week!

**Comment by ralph-tice** [comment]
While you are working on the templates, have you considered adding a component representing a distributed ordered log service?  I see the architecture here as emblematic of the [CQRS pattern](https://martinfowler.com/bliki/CQRS.html).

Typically a high scale system will use Kafka, ActiveMQ, RabbitMQ, Mule types of systems for initial persistence and backend workers subscribe to the queue and persist to the storage layer they're responsible for.  This avoids the 'dual write' problem from occurring synchronously during the write path as well as isolating the write path from the variable latency of multiple storage engines.

Netflix has a good writeup on their usage here: http://techblog.netflix.com/2016/02/evolution-of-netflix-data-pipeline.html

**Comment by donnemartin** [comment]
Hi @ralph-tice good suggestion!  

I haven't considered adding this yet.  Pull requests are welcome :)

**Comment by ralph-tice** [comment]
I'd love to open up a PR and contribute, can you tag me in the commit/PR when you land the Omnigraffle templates in the repo?  Thanks for all your hard work!

**Comment by donnemartin** [comment]
@ralph-tice awesome, sure I'll tag you thanks!

**Comment by donnemartin** [comment]
Just a quick update, I'm getting close to wrapping this up.  Sorry been really busy lately, I hope to have it out end of this week.

**Comment by donnemartin** [comment]
Template and diagrams are now available!  See https://github.com/donnemartin/system-design-primer/pull/48.
