### ISSUE TITLE
add discussion of potential pitfalls of transient caches in concurrent scenarios

### ISSUE THREAD

**Issue by bradclawsie** [donnemartin/system-design-primer#16]
cache tombstones etc

**Comment by donnemartin** [comment]
Hi @bradclawsie thanks for the suggestion!  PRs are welcome :)

**Comment by QuestForGhabby** [comment]
Just meeting guy about using programs today.  Hold on people in coffee shop trolling me.  I rage quit 😘

**Comment by Ashoka33** [comment]
I am new what should i lern to use github
