### ISSUE TITLE
Confusing word play in the definition of AP under CAP theorem portion.

### ISSUE THREAD

**Issue by panth** [donnemartin/system-design-primer#164]
The post says - "Responses return the **most recent version** of the data available on the a node, which **might not be the latest**."

Can this be changed or finetuned ? Maybe something like -

"Responses return the most **readily available version** of the data available on **any** node, which might not be the latest."
Again here we talking about multi-node system ( on account of P of CAP). So in essence there is no assurance that previous WRITE/UPDATE would have cascaded to all nodes thereby giving C (of CAP).  On the other hand the consumer does a look-up and which ever node is hit , returns the data ( or its state)

**Comment by donnemartin** [comment]
@panth sounds good to me, would you like to submit a PR?

**Comment by panth** [comment]
Ok doing so now.

**Comment by neesara** [comment]
@donnemartin Shall I go ahead and make the changes and create a PR?
