### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Eddie-CooRo** [donnemartin/system-design-primer#171]
"Crack the system design interview" Link is broken. Here is the new link to replace https://www.puncsky.com/blog/2016-02-13-crack-the-system-design-interview

**Comment by donnemartin** [comment]
Hi @Eddie-CooRo, do you want to submit a PR?

**Comment by jashgala** [comment]
Can I submit a PR for this?

**Comment by donnemartin** [comment]
Looks like there's a PR already: https://github.com/donnemartin/system-design-primer/pull/180

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/system-design-primer/pull/180
