### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Allaman** [donnemartin/system-design-primer#186]
Maintainer(s): @Allaman

Please check out the [Translations Contributing Guidelines](https://github.com/donnemartin/system-design-primer/blob/master/CONTRIBUTING.md#translations).

Original translations thread: #28 

Interested in helping? Let us know!

---

Hi,

thanks for the awesome information provided in this repo! I would like to contribute by translating the content to German.
I am a native speaker from Germany and I will maintain the German content. Furthermore, I will encourage people to review and/or contribute too.

Here is a list of some top level work packages:

- [x] Fork the repo
- [ ] Submit a PR with the single file README-xx.md
- [ ] Add links to your translation at the top of every README*.md 
  - [ ] [Top-level Readme](https://github.com/donnemartin/system-design-primer/blob/master/README.md)
  - [ ] Check for further README's
- [ ] Translate
  - [ ] [Top-level Readme](https://github.com/donnemartin/system-design-primer/blob/master/README.md)
- [ ] Make a PR

**Comment by donnemartin** [comment]
@Allaman awesome thank you!

**Comment by donnemartin** [comment]
Hi @Allaman: Are you still interested in translating the guide and being the language maintainer?

**Comment by Allaman** [comment]
Hi @donnemartin oh my gosh :facepalm: two years
Well, basically yes. I "just" have to find some time :mag:

**Comment by Clijsters** [comment]
I would love to support you translating this. Is it still in progress?

**Comment by Allaman** [comment]
Hi @Clijsters, unfortunately I have not found time for it so you can say it is still in progress :)

**Comment by Clijsters** [comment]
@donnemartin I'll submit a PR for getting the current maintainer. @Allaman If that's okay I just start translating and you can jump on if you have more time?

**Comment by Allaman** [comment]
sure :+1: @Clijsters

**Comment by JacobK233811** [comment]
@Clijsters @Allaman What's the progress on the German translation? I'm not a native speaker but have extensively studied the language and believe I can be of help dealing with small chunks of the work :)

**Comment by Allaman** [comment]
Hello @JacobK233811 thanks for your offer! Unfortunately,from my side there is no progress :(

**Comment by Allaman** [comment]
@Clijsters @JacobK233811 I decided to start the translation once again. If you want to contribute feel free to contact me :) 
Here is the fork I am going to work on: https://github.com/Allaman/system-design-primer

\cc @donnemartin

**Comment by Clijsters** [comment]
Ditto. I thought I already asked @dominikbraun, because there is a PR open, but I might forgot about that.
I'll coma back to that and when I have enough time, Id create a PR on your fork, @Allaman .

**Comment by Allaman** [comment]
@Clijsters alright looking forward to your PR. We'll work on the 'de' branch :) 

In order to parallelize our work I created [issues](https://github.com/Allaman/system-design-primer/issues) based on all level 2 headers of the original file. So everybody can pick and assign a section so it is transparent who is working on what topic

**Comment by dominikbraun** [comment]
Ok, so we'll use @Allaman's branch and I'm going to close my PR.

**Comment by Allaman** [comment]
@Clijsters @dominikbraun @JacobK233811 ?

 I think we are ready to go :tada: Can you please choose a section you would like to translate from [here](https://github.com/Allaman/system-design-primer/issues) so that we do not work on the same chapter? Thanks :)

**Comment by JacobK233811** [comment]
I can do the Contributing section. I’ll happily comment on the issue, but I’m curious about the extent of each section. Do we follow all of the links within the section and translate the content there too?

If not, completing a single section seems very manageable. Our main translation goal is to get through the README, yes?

Please advise.

JacobK233811

**Comment by Allaman** [comment]
@JacobK233811 I'll suggest that we only translate content that is in the actual repo and is text. So i would not translate images for instance
Yeah - the main goal is the README :)

**Comment by JacobK233811** [comment]
@Allaman I noticed that GitHub no longer hosts your fork, what is the future of the community German translation? I have our progress locally, though I understand the README-de.md never saw completion.
[README-de.md](https://github.com/donnemartin/system-design-primer/files/9594995/README-de.md)

**Comment by Allaman** [comment]
@JacobK233811 I have closed https://github.com/donnemartin/system-design-primer/pull/504 because there is a PR (https://github.com/donnemartin/system-design-primer/pull/577) that was more complete at that time but apparently never got merged.

**Comment by JacobK233811** [comment]
Good to hear, @donnemartin what's the plan to clear off the "needs-review" tag? Should other contributors read and give it the green light?

@Allaman , were the components of #504 incorporated or did it not make sense relative to the quality and completeness of #577 . Hoping to see an official German translation as part of the main repository in the near future :)

**Comment by Allaman** [comment]
@JacobK233811 to be honest I've never checked the quality or completeness of https://github.com/donnemartin/system-design-primer/pull/577 ...

**Comment by JacobK233811** [comment]
I see, hopefully it can get merged soon.

**Comment by LopeKinz** [comment]
i can start to translate.

**Comment by jannismilz** [comment]
Since #577 surprisingly got deleted I reopened it #831 and already made some improvements

**Comment by Allaman** [comment]
closed in favor of https://github.com/donnemartin/system-design-primer/issues/873

**Comment by itsSauraj** [comment]
@donnemartin I would like to reopen German Translation and maintain it as well.
