### ISSUE TITLE
Include this guide with github.com/open-guides ?

### ISSUE THREAD

**Issue by spartanatreyu** [donnemartin/system-design-primer#2]
This would be awesome if this was the platform-agnostic companion guide with the [Open Amazon Web Services](https://github.com/open-guides/og-aws) guide posted and maintained under github.com/open-guides.

**Comment by FourSigma** [comment]
I agree, that would be nice!

**Comment by donnemartin** [comment]
Hi, I'm a big fan of the awesome open-guides/og-aws and helped pitch in with its initial launch.  I'll have to think some more about the suggestion, thanks!
