### ISSUE TITLE
哈佛大学可扩展性讲座 地址无效

### ISSUE THREAD

**Issue by smileusd** [donnemartin/system-design-primer#222]

**Comment by geekgao** [comment]
CS75 (Summer 2012) Lecture 9 Scalability Harvard Web Development David Malan
有效啊，科学上网即可。

**Comment by sqrthree** [comment]
@smileusd The link is valid. You can't access it just because of GFW.

@donnemartin this issue can be closed.

**Comment by donnemartin** [comment]
@geekgao @sqrthree thanks!
