### ISSUE TITLE
Anki decs not easly imported

### ISSUE THREAD

**Issue by senpl** [donnemartin/system-design-primer#223]
When I tried to import anki decs to anki mobile app it states that decks can not be simply imported. I think they should be easly imported with default settings or have description how to import them correctly.

**Comment by mishar** [comment]
i have seen this in mac version of anki too. [screen shot 2018-10-14 at 1 08 37 am](https://user-images.githubusercontent.com/1500693/46912804-b6235380-cf4d-11e8-92fd-f67801a6cf81.png)

**Comment by donnemartin** [comment]
Hi, seems this doesn't fix the issue?  https://github.com/donnemartin/system-design-primer/pull/206
