### ISSUE TITLE
Mutex lock/unlock latency

### ISSUE THREAD

**Issue by mkamilov** [donnemartin/system-design-primer#228]
It is given as 100ns in the table and 25ns in the visualization.

**Comment by saurav-2104** [comment]
Raised three PR's one for each language.

**Comment by mkamilov** [comment]
I wonder what is the source of 100ns and 25ns and which one is right value

**Comment by anonymousedzika** [comment]
I speak indonesia , not english
Pada tanggal 15 Nov 2018 4.13 PM, "Saurav Gupta" <notifications@github.com>
menulis:
