### ISSUE TITLE
Design an exchange (like nasdaq or binance)

### ISSUE THREAD

**Issue by morenoh149** [donnemartin/system-design-primer#281]
Would adding a solution for designing an exchange be welcome? I was asked this once and did not do well.

Some resources:
https://youtu.be/b1e4t2k2KJY
https://around25.com/blog/building-a-trading-engine-for-a-crypto-exchange/
http://bhomnick.net/building-a-simple-limit-order-in-go/

**Comment by donnemartin** [comment]
Hi @morenoh149, feel free to submit a pull request adding a line item in this section:

https://github.com/donnemartin/system-design-primer#additional-system-design-interview-questions
