### ISSUE TITLE
Point this course at resume?

### ISSUE THREAD

**Issue by artkpv** [donnemartin/system-design-primer#285]
Hi! Thanks for maintaining this list of important work on system design. I wonder how one can write about this course at the resume / CV? If it goes to the Education section then it needs some credentials. If in the Projects section then it needs some measurable outcome.

**Comment by dharmaturtle** [comment]
Make a project implementing these ideas or use these principles at work. Credentials/education count for little in the programmer world.

**Comment by donnemartin** [comment]
Hi @artkpv I'd go the route of applying what you learn from this guide in some manner.
