### ISSUE TITLE
Repo internal links are broken

### ISSUE THREAD

**Issue by letientai299** [donnemartin/system-design-primer#3]
It seems that you have changed repo name from `system-design-primer-interview` to `system-design-primer`, while using hard link (`https://github.com/donnemartin/...`)  inside the `readme`s. 

I suggest to user Github relative link schema instead.

**Comment by donnemartin** [comment]
Hi @letientai299, it looks like the links for the exercises/solutions are broken, I'll fix them.  Thanks for reporting!

**Comment by letientai299** [comment]
FYI, you can replace

```
https://github.com/donnemartin/system-design-primer-interview#index-of-system-design-topics-1
```
with 
```
/README.md#index-of-system-design-topics-1
```

**Comment by donnemartin** [comment]
@letientai299 I fixed the broken links as the first pass.  I missed your [tip](https://github.com/donnemartin/system-design-primer/issues/3#issuecomment-285239849), we can make them relative in the next pass.  I've opened up https://github.com/donnemartin/system-design-primer/issues/6 to keep track.

Thanks!
