### ISSUE TITLE
Change Zookeeper as example for service discovery

### ISSUE THREAD

**Issue by mad01** [donnemartin/system-design-primer#31]
Using Zookeeper as a example of service discovery might not be a god idea. Why? The way you run and manage zookeeper is hard, the way zookeeper knows that a service is healthy is a bit fragile and does not allow node failure in the ZK cluster. Using something like [consul](https://www.consul.io/docs/index.html)  as the example were the health checking is done differently  and is pull based makes it more robust and is probably a better example to point to

zookeeper works fine if you are looking for a AP solution for master elections and things like that but for service discovery it's not that suitable

using consul means that you need a http endpoint that consul can health check 
using zookeeper means that you need application logic to hold a tcp connection open

**Comment by donnemartin** [comment]
Hi @mad01, thanks for the feedback!

Please feel free to submit a PR to help us get started.  The [Service Discovery](https://github.com/donnemartin/system-design-primer#service-discovery) section is also very thin at the moment, it could also use a bit more detail if you're up for it :)

**Comment by donnemartin** [comment]
Merged with https://github.com/donnemartin/system-design-primer/pull/36.
