### ISSUE TITLE
Availability patterns description

### ISSUE THREAD

**Issue by njacharya** [donnemartin/system-design-primer#313]
A description is incomplete. It should mention:

These patterns are not competing, but complementing each other. To achieve availability, one needs both fail-over and replication. 

right after

"There are two main patterns to support high availability: fail-over and replication. "

**Comment by acbnelsalvador** [comment]
Gracias por los que comenten pero soy nuevo en esto y estoy en prueba y error aprendiendo.

**Comment by donnemartin** [comment]
Hi @njacharya good catch.  Anyone want to submit a pull request?  I think changing this:

>There are two main patterns to support high availability: fail-over and replication.

To this:

>There are two complementary patterns to support high availability: fail-over and replication.

Would bring more clarity.

**Comment by njacharya** [comment]
https://github.com/donnemartin/system-design-primer/pull/439

**Comment by nacharya-msft** [comment]
> Hi @njacharya good catch. Anyone want to submit a pull request? I think changing this:
> 
> > There are two main patterns to support high availability: fail-over and replication.
> 
> To this:
> 
> > There are two complementary patterns to support high availability: fail-over and replication.
> 
> Would bring more clarity.

 created new pull request: https://github.com/donnemartin/system-design-primer/pull/439
