### ISSUE TITLE
OSI stands for Open Systems Interconnection (not Open Source Interconnection)

### ISSUE THREAD

**Issue by art-in** [donnemartin/system-design-primer#335]
![4158c3ce816fe61d664672052cf09e79](https://user-images.githubusercontent.com/671082/68393138-704eb400-017c-11ea-9510-a9d767390457.png)

Should be "OSI (Open Systems Interconnection) 7 Layer Model"

https://www.iso.org/ics/35.100/x/

**Comment by iravitejakumar** [comment]
Hi @donnemartin Can you review the PR which I sent to resolve this issue ?
