### ISSUE TITLE
Awesome. 借楼招个人

### ISSUE THREAD

**Issue by jiffies** [donnemartin/system-design-primer#346]
字节跳动教育线新项目，大投入，千亿级市场，服务端工程师大量缺口，各级别都要。项目主要使用Golang/Python，但是语言不做要求，可以来了再学。研发直招渠道，快速反馈，支持年前面试(可以远程面试)，年后报道，北京、上海都有HC。完整简历请投邮箱 lichengqian@bytedance.com。邮件标题：在线教育+姓名

**Comment by sqrthree** [comment]
An ad, and it's nothing to do with the current project. @donnemartin
