### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by Kazaf123** [donnemartin/system-design-primer#352]
When I read the pull request, sometimes it is hard to read, so I suggest that update a Pull Request Template will make them more readable. Such as:
######Description

######Check List

######My PR Type is:

Thank you!!

**Comment by mihaimaruseac** [comment]
Seems to be spam
![VCA6DzWKgeZ](https://user-images.githubusercontent.com/323199/72463619-84202300-3788-11ea-9d4b-08ac8683f524.png)
