### ISSUE TITLE
Weighted Round Robin in DNS section points to a broken link.

### ISSUE THREAD

**Issue by ghost** [donnemartin/system-design-primer#354]
This is the link, it points to: https://g33kinfo.com/round-robin-vs-weighted-round-robin-lb/

**Comment by suryart** [comment]
This is fixed in https://github.com/donnemartin/system-design-primer/pull/351

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/system-design-primer/pull/351.
