### ISSUE TITLE
Is there a formula which can give an answer about ..

### ISSUE THREAD

**Issue by assmdx** [donnemartin/system-design-primer#389]
I mean, 
for example  I want to build a sytem, and I know about 100 request/sencond to my server and 20 write sql/second,

is there an formula to tell me how to design this system,and how to choose hardware??

**Comment by devdil** [comment]
Depends upon a lot of things, your data access pattern , your caching
patterns scale of users, reads vs writes.

**Comment by donnemartin** [comment]
There isn't a straightforward answer to this question, check out the exercises for examples on how one might build intuition around this.
