### ISSUE TITLE
Replace "master" and "slave" terms

### ISSUE THREAD

**Issue by ianbrayoni** [donnemartin/system-design-primer#397]
Inspired by this [change request](https://bugs.python.org/issue34605)

`master` and `slave` are a reminder of a painful world history, that is, they are racially charged terms.

I move that we purge these terms in favour of:

- `primary`, `replica`
- `primary`, `secondary`

Popular open-source communities have adopted newer references:
https://github.com/django/django/pull/2692
https://github.com/antirez/redis/issues/3185
https://issues.apache.org/jira/browse/COUCHDB-2248

**Comment by Willempipi** [comment]
You are is sooo racist! Let me guess, they should also ban the word "black"? 

Please stop keeping racism alive with this stupid shit.

**Comment by CamAnNguyen** [comment]
It's the keywords/terminologies to related technical area. You can try to search for "primary-replica architecture" and see the [results](https://www.google.com/search?q=primary-replica+architecture&oq=primary+replica+arch&aqs=chrome.1.69i57j0.2433j0j7&sourceid=chrome&ie=UTF-8).

**Comment by donnemartin** [comment]
Thanks @ianbrayoni, please see https://github.com/donnemartin/system-design-primer/pull/217.

**Comment by ianbrayoni** [comment]
> Thanks @ianbrayoni, please see #217.

Great!
