### ISSUE TITLE
Normally, the passive server won't take over the IP address of active server in the case of failover

### ISSUE THREAD

**Issue by ssquan** [donnemartin/system-design-primer#402]
![Uploading image.png…]()

The passive server may become active server,  but normally,  they won't change their IP address.

**Comment by sj123050037** [comment]
The passive server takes the IP active one when it finds the active one dead, this is how the new traffic goes to the passive one. Read about the concept of elastic IPs in AWS.

**Comment by ssquan** [comment]
> The passive server takes the IP of the active one when it finds the active one dead, this is how the new traffic goes to the passive one. Read about the concept of elastic IPs in AWS.

Is Elastic Ip in AWS the IP address of Nginx-like server?

**Comment by sj123050037** [comment]
Check out this lecture at time 1:20:40, where the professor talks about this concept. https://www.youtube.com/watch?v=-W9F__D3oY4&list=LL7DWD8TZslgDI9Oo2pM6mfQ&index=6&t=14s

Also, check out - How the HA Solution Works here for Nginx where they talk about the virtual ip address - https://www.nginx.com/products/nginx/high-availability/

**Comment by ssquan** [comment]
Thanks a lot,  @sj123050037, awesome lecture!  It's great to use a virtual IP address to handle the single point failure of Load Balance servers.
