### ISSUE TITLE
Python iterations

### ISSUE THREAD

**Issue by D3ADB0N3S** [donnemartin/system-design-primer#419]
Hello please may I have some help I need help with this question that I find difficult and my teacher only showed examples not these ones and he hasn't explained since we are in qurantine. Write a program that reads in a series of numbers and adds them up until the user enters zero (this stopping value is often called a rogue value).

**Comment by BalajiG2000** [comment]
@D3ADB0N3S  I hope this is the code you are expecting
[https://github.com/BalajiG2000/Basic_programming/blob/master/add_series_till_roguevalue.py](url)

**Comment by D3ADB0N3S** [comment]
@BalajiG2000 There is an intended block on this line of code here user_input = int(input("Enter a number:"))

**Comment by BalajiG2000** [comment]
@D3ADB0N3S  Now it's fine. This error indicates that there is a problem with indentation.
You can check out this code here:
[https://github.com/BalajiG2000/Basic_programming/blob/master/add_series_till_roguevalue.py](https://github.com/BalajiG2000/Basic_programming/blob/master/add_series_till_roguevalue.py)
And make sure you use a python version of 3 or above
user_input = None
total_sum = 0
while user_input != 0:
    user_input = int(input("Enter a number:"))
    total_sum = total_sum + user_input
print("The total sum of the numbers are {}".format(total_sum))
