### ISSUE TITLE
Tkinter Library

### ISSUE THREAD

**Issue by guillermocol** [donnemartin/system-design-primer#422]
Hi, I am trying to use Tkinter library for Python in Centos 7 with no luck. I was before using it with Ubuntu and no issues, but with Centos even I installed it, it shows when I run the code that the tkinter library doesn't exist.

Any recommendations, would you use a different library for this purpose (creating menus in applications)?

Thank you,
guillermo

**Comment by guillermocol** [comment]
Hi donnemartin, let me know who you could refer for this topic. thank you.

**Comment by donnemartin** [comment]
Hi @guillermocol, sorry this is not the right repo for this topic.
