### ISSUE TITLE
About python

### ISSUE THREAD

**Issue by Deniswanja** [donnemartin/system-design-primer#424]
Am an upcoming programmer and I have challenges on how to code using python how will you help me

**Comment by crimeminister** [comment]
This is not the place for the sort of help I think you're looking for. I would suggest giving [this book](https://diveintopython3.net/) a read and joining one of the many programmer instructional and self-help communities. A site like [StackOverflow](https://stackoverflow.com/) comes to mind. Good luck.

**Comment by Azooze0533** [comment]
- #@hgtr_****_
