### ISSUE TITLE
what's the drawing tool on reademe

### ISSUE THREAD

**Issue by jasonhubs** [donnemartin/system-design-primer#44]
Hi,it's very beautiful -the frame about the system-design，and i want to know that which tool to draw it!
   thank you!

**Comment by bowin** [comment]
curious   +1

**Comment by donnemartin** [comment]
Hi @jasonhubs @bowin, thanks for the feedback!  I use OmniGraffle, more info can be found in https://github.com/donnemartin/system-design-primer/issues/15.

**Comment by jasonhubs** [comment]
thank you! @donnemartin
