### ISSUE TITLE
Please Add Resources for Low-Level System Design.

### ISSUE THREAD

**Issue by prasadgujar** [donnemartin/system-design-primer#465]
Hello,  @donnemartin 
Thanks for the great compilation for the system design resources but one important thing is missing from this as a great collection of resources is Low-Level Design resources.
taking inspiration from the system design primer I created the low-level design primer which is similar to the system design primer.
Please add the below resources for the low-level system design as well.
Resources: https://github.com/prasadgujar/low-level-design-primer
Thank you :)

**Comment by gyanprakash0221** [comment]
Is this pr still open, I needed to add some of the resources for the low-level system design

**Comment by prasadgujar** [comment]
@donnemartin can you please review this PR and merge it out?

**Comment by prasadgujar** [comment]
@donnemartin @satob @lzyzsd any updates on this?
