### ISSUE TITLE
Which tool has been used to create the Diagram?

### ISSUE THREAD

**Issue by Jeshwanth** [donnemartin/system-design-primer#54]
Hello,
Just for an information, and the diagram looks really good. 

Can you please share which tool you used to create the diagram ?

Thanks

**Comment by Jeshwanth** [comment]
Omnigraffle.

Found in https://news.ycombinator.com/item?id=13823979

**Comment by donnemartin** [comment]
Hi @Jeshwanth, yes it's OmniGraffle, for more detail check out https://github.com/donnemartin/system-design-primer/issues/15.  Thanks!
