### ISSUE TITLE
a broken link

### ISSUE THREAD

**Issue by zhulongcheng** [donnemartin/system-design-primer#58]
> Coding deck

this link not work

**Comment by donnemartin** [comment]
Hi @zhulongcheng thanks for the bug report!  The link should be:

https://github.com/donnemartin/interactive-coding-challenges/blob/master/anki_cards/Coding.apkg

Interested in submitting a pull request?

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/system-design-primer/pull/59.
