### ISSUE TITLE
Python Program Quetion

### ISSUE THREAD

**Issue by VijayRathod20** [donnemartin/system-design-primer#619]
A library charges a fine for every book returned late. For first 5 days the 
fine is 50 paisa, for 6-10 days fine is one rupee and above 10 days fine is 5 
rupees. If you return the book after 30 days your membership will be 
cancelled. Write a Python program to accept the number of days the member is late 
to return the book and display the fine or the appropriate message.

**Comment by Harsh-2200** [comment]
[Uploading library.py…]()

**Comment by VaishnaviJahagirdar3** [comment]
Can I do this?

**Comment by VijayRathod20** [comment]
Yes

**Comment by ecargsid-eht** [comment]
can i do this please?

**Comment by fxchulo123** [comment]
I want to participate

**Comment by KiranQureshi53** [comment]
@VaishnaviJahagirdar3, are you still looking for the code? I am willing to do it.

**Comment by VijayRathod20** [comment]
No
