### ISSUE TITLE
Weighted round robin link in DNS section is dead

### ISSUE THREAD

**Issue by mleers** [donnemartin/system-design-primer#650]
The link in question: https://www.g33kinfo.com/info/round-robin-vs-weighted-round-robin-lb
Location in course: https://github.com/donnemartin/system-design-primer/blob/master/README.md#domain-name-system
Potential replacement: https://www.jscape.com/blog/load-balancing-algorithms

**Comment by donnemartin** [comment]
Fixed with #651
