### ISSUE TITLE
Inaccuracy in Twitter timeline and search example

### ISSUE THREAD

**Issue by tangkangkai** [donnemartin/system-design-primer#79]
In Calculate usage, 

6,000 tweets per second
**15 billion tweets delivered on fanout per month** * (400 requests per second / 1 billion requests per month)
60 thousand tweets delivered on fanout per second
**150 billion tweets delivered on fanout per month** * (400 requests per second / 1 billion requests per month)

We probably want to use "15 billion tweets per month" instead.

**Comment by donnemartin** [comment]
Hi @tangkangkai, nice catch!  I think line 79 should say the following, to be consistent with line 44.

    * 15 billion tweets per month * (400 requests per second / 1 billion requests per month)

Are you interested in submitting a pull request?

**Comment by tangkangkai** [comment]
Requested
