### ISSUE TITLE
Can anybody tell me how to draw a pretty image like this? Which tool to use?

### ISSUE THREAD

**Issue by rrxmzl** [donnemartin/system-design-primer#832]
<img width="617" alt="jj3A5N8" src="https://github.com/donnemartin/system-design-primer/assets/152613169/4aa9e337-747b-4bc8-a237-68de91a4ea51">

**Comment by Chad-Ballay** [comment]
I believe these images are made using Omnigraffle.

**Comment by Chad-Ballay** [comment]
Yep.  It looks like I was right.  Omnigraffle.

**Comment by rrxmzl** [comment]
thanks so much @Chad-Ballay
