### ISSUE TITLE
Fixing Markdown Lint related issues in readme.md file.

### ISSUE THREAD

**Issue by pallavsharma** [donnemartin/system-design-primer#875]
**Fixing Markdown Lint-related issues in readme.md file.**

Using a markdown-lint extension to highlight lint-related issues.

eg:
MD028 - Blank line inside blockquote
MD046 - Code block style
MD001 - Heading levels should only increment by one level at a time
MD040 - Fenced code blocks should have a language specified
MD033 - Inline HTML

**Comment by pallavsharma** [comment]
Need access to push the code.

**Comment by nkroker** [comment]
> Need access to push the code.
Hi @pallavsharma I think this might help
Reference: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project
