### ISSUE TITLE
Difference between pull and push CDN

### ISSUE THREAD

**Issue by shanSyapse** [donnemartin/system-design-primer#90]
From this source
http://www.travelblogadvice.com/technical/the-differences-between-push-and-pull-cdns/, the push CDN is better for high traffic websites, and pull cdn is better for low traffic websites.  However, it is stated the opposite way in your description. It is probably a typo on your article

**Comment by NathanHeffley** [comment]
Just saying, but a blog about travel blogs is probably not a super reliable source. From reading over both resources, it sounds like that article has it backwards and the explanation given in this GitHub repo sounds more reasonable.

**Comment by donnemartin** [comment]
Hi, I took a quick look at the article, it says this (emphasis mine):

>A **pull CDN can help high-traffic**-small-download sites by keeping the most popular content on CDN servers.

This seems to be opposite from your interpretation of the article:

>...push CDN is better for high traffic websites, and pull cdn is better for low traffic websites

**Comment by geekykant** [comment]
@donnemartin Would be better to add this comment in brackets across this [blog source link](https://github.com/donnemartin/system-design-primer#sources-and-further-reading-6).
It's confusing for users reading both.
